[user]
name = "Gregory Anders"
email = "greg@gpanders.com"

[ui]
default-command = "status"

[aliases]
l = ["log"]
ll = ["log", "-T", "builtin_log_detailed", "-r", "..@"]
d = ["diff"]
rb = ["rebase"]
b = ["branch"]
g = ["git"]

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  "\nJJ: ------------------------ >8 ----------------------\n",
  diff.git(),
)
'''
